### ISSUE TITLE
App Framework: 

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-operator#897]
### Please select the type of request

Bug

### Tell us more

**Describe the request**
- Bug - If i remove or change an `appSources` after the CRD has been created the splunk-operator-controller will crash in a `crashLoopBackoff`

**Expected behavior**
- You should be able to tell the operator to no longer monitor an `appSources` and apply that configuration to the CRD after creation. 

**Splunk setup on K8S**
- I've confirmed this happens on Standalone and Licensemasters CRD, I expect it happens on all CRDs.

**Reproduction/Testing steps**
- Create a instance with an `appSources` defined then remove one of the `appSources`.

Example:
```yaml
---
apiVersion: enterprise.splunk.com/v3
kind: LicenseMaster
metadata:
  name: k8s-lic
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  image: splunk/splunk:8.2.1
  volumes:
  - name: licenses
    configMap:
      name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: local
    appSources:
      - name: k8sApps
        location: k8sApps/
      - name: licApps/
        location: licApps/
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: aws
        path: splunk-k8s-apps/
        endpoint: https://s3-us-east-1.amazonaws.com
        region: us-east-1
```
- Run `kubectl create -f file-name.yaml`
- Comment out one of the `appSources` 
- Run `kubectl apply -f file-name.yaml`
- monitor the splunk-operator-controller pod

**K8s environment**
- AWS EKS

**Additional context(optional)**
LOGS:

```text
2022-09-13T17:01:07.473431703Z	INFO	controller.licensemaster.ValidateAppFrameworkSpec	App framework configuration is valid{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default"}
2022-09-13T17:01:07.473465498Z	INFO	controller.licensemaster.HasAppRepoCheckTimerExpired	App repo polling interval timer has expired	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "LastAppInfoCheckTime": "1663087312", "current epoch time": "1663088467"}
2022-09-13T17:01:07.473473199Z	INFO	controller.licensemaster.initAndCheckAppInfoStatus	Checking status of apps on remote storage...	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "name": "k8s-lic", "namespace": "default"}
2022-09-13T17:01:07.473481099Z	INFO	controller.licensemaster.GetAppListFromS3Bucket	Getting the list of apps from remote storage...	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "name": "k8s-lic", "namespace": "default"}
2022-09-13T17:01:07.473491532Z	INFO	controller.licensemaster.GetRemoteStorageClient	No secrectRef provided.  Attempt to access remote storage client without access/secret keys	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "name": "k8s-lic", "namespace": "default"}
2022-09-13T17:01:07.473499307Z	INFO	controller.licensemaster.GetRemoteStorageClient	Creating the client	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "name": "k8s-lic", "namespace": "default", "volume": "volume_app_repo", "bucket": "splunk-k8s-apps", "bucket path": "k8sApps/"}
2022-09-13T17:01:07.473507073Z	INFO	controller.licensemaster.InitAWSClientSession	No valid access/secret keys.  Attempt to connect without them	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default"}
2022-09-13T17:01:07.473703992Z	INFO	controller.licensemaster.InitAWSClientSession	AWS Client Session initialization successful.{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "region": "us-east-1", "TLS Version": "TLS 1.2"}
2022-09-13T17:01:07.473721915Z	INFO	controller.licensemaster.GetAppsList	Getting Apps list	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "AWS S3 Bucket": "splunk-k8s-apps"}
2022-09-13T17:01:07.47491398Z	INFO	controller.searchheadcluster	Starting workers	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "SearchHeadCluster", "worker count": 15}
2022-09-13T17:01:07.474992706Z	INFO	controller.indexercluster	Starting workers	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "IndexerCluster", "worker count": 15}
2022-09-13T17:01:07.475795401Z	INFO	controller.standalone	Starting workers	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "Standalone", "worker count": 15}
2022-09-13T17:01:07.475897032Z	INFO	controller.monitoringconsole	Starting workers	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "MonitoringConsole", "worker count": 15}
2022-09-13T17:01:07.562940807Z	INFO	controller.licensemaster.initAndCheckAppInfoStatus	Apps List retrieved from remote storage	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "name": "k8s-lic", "namespace": "default", "App Source": "k8sApps", "Content": [{"Etag":"7cc5cbb4416d564e27223f2702b2c15f","Key":"k8sApps/splunk-add-on-for-microsoft-windows.tgz","LastModified":"2022-09-08T14:55:19Z","Size":126059,"StorageClass":"STANDARD"}]}
2022-09-13T17:01:07.563246324Z	INFO	controller.licensemaster.handleAppRepoChanges	received App listing	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "for App sources": 1}
2022-09-13T17:01:07.56335734Z	DPANIC	controller.licensemaster.handleAppRepoChanges	odd number of arguments passed as key-value pairs for logging	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "ignored key": "Reason: App source is mising in config or remote listing"}
github.com/splunk/splunk-operator/pkg/splunk/enterprise.initAndCheckAppInfoStatus
	/workspace/pkg/splunk/enterprise/util.go:1389
github.com/splunk/splunk-operator/pkg/splunk/enterprise.ApplyLicenseManager
	/workspace/pkg/splunk/enterprise/licensemaster.go:65
github.com/splunk/splunk-operator/controllers.glob..func3
	/workspace/controllers/licensemaster_controller.go:114
github.com/splunk/splunk-operator/controllers.(*LicenseMasterReconciler).Reconcile
	/workspace/controllers/licensemaster_controller.go:104
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
panic: odd number of arguments passed as key-value pairs for logging

goroutine 527 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0008fc480, {0xc0003d7140, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).DPanic(0x1abedfe, {0x1b263a4, 0x180b1c0}, {0xc0003d7140, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:220 +0x59
github.com/go-logr/zapr.(*zapLogger).handleFields(0xc000f0bc80, 0x0, {0xc000f0bd10, 0x3, 0x40af7d}, {0x0, 0x19a6920, 0x1})
	/go/pkg/mod/github.com/go-logr/zapr@v1.2.0/zapr.go:145 +0xdea
github.com/go-logr/zapr.(*zapLogger).Info(0xc000f0bc80, 0x0, {0x1abcf32, 0x0}, {0xc000f0bd10, 0x3, 0x3})
	/go/pkg/mod/github.com/go-logr/zapr@v1.2.0/zapr.go:198 +0x8d
github.com/go-logr/logr.Logger.Info({{0x1e929a8, 0xc000f0bc80}, 0x8}, {0x1abcf32, 0xa}, {0xc000f0bd10, 0x3, 0x3})
	/go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:249 +0xd0
github.com/splunk/splunk-operator/pkg/splunk/enterprise.handleAppRepoChanges({0x1e75350, 0xc000ae9c80}, {0x4, 0x1af15f9}, {0x1ecb200, 0xc000a90800}, 0xc000a90ea8, 0xc000837bc0, 0x0)
	/workspace/pkg/splunk/enterprise/util.go:983 +0x717
github.com/splunk/splunk-operator/pkg/splunk/enterprise.initAndCheckAppInfoStatus({0x1e75350, 0xc000ae9c80}, {0x7f993d2903b8, 0xc0003d3310}, {0x1ecb200, 0xc000a90800}, 0xc000a90e28, 0xc000a90ea8)
	/workspace/pkg/splunk/enterprise/util.go:1389 +0x736
github.com/splunk/splunk-operator/pkg/splunk/enterprise.ApplyLicenseManager({0x1e75350, 0xc000ae9c80}, {0x7f993d2903b8, 0xc0003d3310}, 0xc000a90800)
	/workspace/pkg/splunk/enterprise/licensemaster.go:65 +0x21e
github.com/splunk/splunk-operator/controllers.glob..func3({0x1e75350, 0xc000ae9c80}, {0x1eaa0f8, 0xc0003d3310}, 0x5)
	/workspace/controllers/licensemaster_controller.go:114 +0x59
github.com/splunk/splunk-operator/controllers.(*LicenseMasterReconciler).Reconcile(0xc00037d638, {0x1e75350, 0xc000ae9c80}, {{{0xc0009f4867, 0x7}, {0xc0009f4877, 0x7}}})
	/workspace/controllers/licensemaster_controller.go:104 +0x56a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00075c420, {0x1e75350, 0xc000ae9bc0}, {{{0xc0009f4867, 0x19ef2a0}, {0xc0009f4877, 0x413c34}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00075c420, {0x1e752a8, 0xc00067d280}, {0x190a5c0, 0xc0000aeba0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00075c420, {0x1e752a8, 0xc00067d280})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by sgontla** [comment]
@satellite-no , issue is with the log message, where we are passing even number of argument values to the logger, when it is expecting odd number.  
```
2022-09-13T17:01:07.56335734Z	DPANIC	controller.licensemaster.handleAppRepoChanges	odd number of arguments passed as key-value pairs for logging	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "kind": "LicenseMaster", "name": "k8s-lic", "namespace": "default", "ignored key": "Reason: App source is mising in config or remote listing"}
github.com/splunk/splunk-operator/pkg/splunk/enterprise.initAndCheckAppInfoStatus

We will fix it.

**Comment by satellite-no** [comment]
Thank you for the clarification!

**Comment by oblogic7** [comment]
We are running into this issue as well.  Is there an ETA for when the release will drop?

**Comment by gaurav-splunk** [comment]
The fix for this will be part of the next release which will be out sometime around Nov 1st.

**Comment by iaroslav-nakonechnikov** [comment]
@gaurav-splunk are there any ETA? 1st november passed and 2.1.1 was released, but issue is still here

**Comment by kashok-splunk** [comment]
Hi @iaroslav-nakonechnikov 

The changes to the logging were made with this PR https://github.com/splunk/splunk-operator/pull/898. I confirmed changes are present in the 2.1.1 release. Do you still see the same issues with the 2.1.1 release?

**Comment by gaurav-splunk** [comment]
Hi @iaroslav-nakonechnikov , I tested the changes myself with 2.1.1 release and I don't see the issue in the current release.

**Comment by iaroslav-nakonechnikov** [comment]
@kashok-splunk  @gaurav-splunk yes, i've even raised a ticket in internal servicedesk: case number 3141284

**Comment by iaroslav-nakonechnikov** [comment]
@gaurav-splunk @kashok-splunk i see "odd number issue"  is fixed on "2.2.0" and "edge" labels.

**Comment by akondur** [comment]
Hi @iaroslav-nakonechnikov , per the [comment](https://github.com/splunk/splunk-operator/issues/897#issuecomment-1406593187) above can we close the issue?

**Comment by satellite-no** [comment]
@akondur close it out. 😁
